trainingInput:
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 4
    maxParallelTrials: 2
    hyperparameterMetricTag: mse
    params:
    - parameterName: hidden-layers
      type: DISCRETE
      discreteValues:
      - 1
      - 2
      - 3
      - 4
    - parameterName: units
      type: DISCRETE
      discreteValues:
      - 5
      - 10
      - 16
      - 32
      - 64